=== WSUCptSCapstone-Fall2022Spring2023/index-fullstackapp/index-editor-app/index-editor-app-engine/JsonSchemas/indeximagesSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "events": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "members": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "news": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "specialties": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "Resources": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  "required": [ "events", "members", "news", "specialties", "Resources" ]
}

=== WSUCptSCapstone-Fall2022Spring2023/index-fullstackapp/index-editor-app/index-editor-app-engine/JsonExamples/indeximages.json
{
  "events": [ "https://index-webapp.s3.amazonaws.com/img/eventimages/ParkinsonsSupportGroupCDA.png", "https://index-webapp.s3.amazonaws.com/img/eventimages/StrokeSupportGroupImage.png" ],
  "members": [ "https://index-webapp.s3.amazonaws.com/img/memberimages/JoleneMemberImage.png", "https://index-webapp.s3.amazonaws.com/img/memberimages/ZilarMemberImage.jpg" ],
  "news": [ "https://index-webapp.s3.amazonaws.com/img/newsimages/FromTheEditor.png", "https://index-webapp.s3.amazonaws.com/img/newsimages/InterstateConnections.png", "https://index-webapp.s3.amazonaws.com/img/newsimages/Screen-Shot-2022-10-25-at-1.54.09-PM-338x225.jpg", "https://index-webapp.s3.amazonaws.com/img/newsimages/Screen-Shot-2021-01-04-at-1.14.16-PM-338x225.png" ],
  "specialties": [ "https://index-webapp.s3.amazonaws.com/img/specialtyimages/HousingAdvocacyAndAssistance.png", "https://index-webapp.s3.amazonaws.com/img/specialtyimages/IndependentLivingSkills.png", "https://index-webapp.s3.amazonaws.com/img/specialtyimages/InformationAndReferral.png" ],
  "Resources": [ "https://dacnw.org/wp-content/uploads/2014/05/goal_42_transitionnew_page-300x200.png", "https://dacnw.org/wp-content/uploads/2014/05/goal_42_transitionnew_page-300x200.png", "https://dacnw.org/wp-content/uploads/2014/05/goal_42_transitionnew_page-300x200.png" ]
}
