=== WSUCptSCapstone-Fall2022Spring2023/index-fullstackapp/index-editor-app/index-editor-app-engine/JsonSchemas/membersSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "pageDescription": {
      "type": "string",
      "minLength": 1
    },
    "applicationLink": {
      "type": "string",
      "minLength": 1
    },
    "phraseLink": {
      "type": "string",
      "minLength": 1
    },
    "boardMembers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "position": {
            "type": "string",
            "minLength": 1
          },
          "image": {
            "type": "string",
            "minLength": 1
          },
          "bioLink": {
            "type": "string",
            "minLength": 1
          },
          "bioDescription": {
            "type": "string",
            "minLength": 1
          },
          "bioQuote": {
            "type": "string",
            "minLength": 1
          },
          "employeeSince": {
            "type": "string",
            "minLength": 1
          },
          "officeLocation": {
            "type": "string"
          },
          "officeLink": {
            "type": "string"
          },
          "specialties": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                },
                "link": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": [ "name", "link" ]
            }
          },
          "created_on": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "name",
          "position",
          "image",
          "bioLink",
          "bioDescription",
          "bioQuote",
          "employeeSince",
          "officeLocation",
          "officeLink",
          "specialties",
          "created_on"
        ]
      }
    }
  },
  "required": [
    "pageDescription",
    "applicationLink",
    "phraseLink",
    "boardMembers"
  ]
}

=== WSUCptSCapstone-Fall2022Spring2023/index-fullstackapp/index-editor-app/index-editor-app-engine/JsonExamples/members.json
{
  "pageDescription": "Disability Action Center NW, Inc. thrives upon the truly diverse and committed team of which it is made. Our talented board of directors is no exception to both our determination to effect change and our commitment to excellence. If you are interested in serving on this board, please fill out the  board-application",
  "applicationLink": "https://dacnw.org/wp-content/uploads/2014/04/Board-Application.pdf",
  "phraseLink": "board-application",
  "boardMembers": [
    {
      "name": "Christopher Zilar",
      "position": "Index Advisory Committee Member",
      "image": "https://dacnw.org/wp-content/uploads/2022/01/Christopher-Zilar-400x400.jpg",
      "bioLink": "/staff/christopher-zilar/",
      "bioDescription": "Christopher Zilar – has some knowledge of ADA requirements and works for the Spokane Tribe of Indians as director of Vocational Rehabilition.  Passionate about diversity and inclusion, he is very interested in the basis of the Independent Living Philosophy. Not a surprise since his all-time hero is Rev. Dr. Martin Luther King, Jr.  He doesn’t let a disability get in the way of enjoying time with his family and is a life-long learner. “You can’t go wrong if you trust your passions, and follow your bliss!”",
      "bioQuote": "“You can’t go wrong if you trust your passions, and follow your bliss!”",
      "employeeSince": "2022",
      "officeLocation": "",
      "officeLink": "",
      "specialties": [
        {
          "name": "Board Members",
          "link": "/about"
        }
      ],
      "created_on": "1/20/2022"
    },
    {
      "name": "Jolene Cliffe",
      "position": "Independent Living Advocate",
      "bioLink": "/staff/jolene-cliffe/",
      "image": "https://dacnw.org/wp-content/uploads/2022/07/Jolene-Cliffe-400x400.jpg",
      "bioDescription": "DAC NW is excited to add Jolene to our staff. She brings plenty of experience with her. She has been living with multiple diagnosis for the past 8 years and brings her experience with peer support, independent living skills, and assistive technology from the LC Valley Adult Resource Center. She loves the tremendous sense of community you can build at a Center for Independent Living. Community has given her a family she never knew she needed, a great support network, and the ability to give back. These things can improve your self-worth. Jolene understands the value of not allowing anyone to silence you, especially about things that matter. Sometimes one person standing up is all it takes for others to do the same.",
      "bioQuote": "“One day you will tell the story of how you overcame what you went through and it will be someone else’s survival guide.” ~ Brene Brown.",
      "employeeSince": "2022",
      "officeLocation": "Lewiston, ID",
      "officeLink": "https://dacnw.org/contact/lewiston-id/",
      "specialties": [
        {
          "name": "Housing Advocacy & Assistance",
          "link": "/programs-services/housing-home-modification-and-shelter-services/"
        },
        {
          "name": "Independent Living Skills",
          "link": "/programs-services/life-skills-training/"
        },
        {
          "name": "Individual & Community Advocacy",
          "link": "/programs-services/advocacy/"
        },
        {
          "name": "Information and Referral",
          "link": "/programs-services/information-and-refferal/"
        },
        {
          "name": "Peer Advocacy Counseling",
          "link": "/programs-services/peer-support/"
        }
      ],
      "created_on": "1/19/2022"
    }
  ]
}
